wandb_version: 1

name:
  desc: null
  value: pugcn-baseline
model_config:
  desc: null
  value:
    r: 4
    k: 16
    dilations:
    - 1
    - 2
    - 4
    n_idgcn_blocks: 3
    channels: 64
    n_dgcn_blocks: 3
    use_bottleneck: true
    use_pooling: true
    use_residual: true
    conv: edge
    pool_type: mean
    dynamic: false
    use_refiner: false
    upsampler: nodeshuffle
    hierarchical: false
train_config:
  desc: null
  value:
    batch_size: 64
    epochs: 10
    optimizer: adam
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    save_every: 5
    augment: true
    loss_fn: cd
    k_loss: 4
data_config:
  desc: null
  value:
    path: ./data/PU1K/train/pu1k_poisson_256_poisson_1024_pc_2500_patch50_addpugan.h5
    num_point: 256
    skip_rate: 1
    use_randominput: true
    rng_seed: 42
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745618773
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
